export const AUTH_GITHUB_SUCCESS = 'AUTH_GITHUB_SUCCESS';
export const REQUESTS = 'REQUESTS';
export const STOP_LOADING = 'STOP_LOADING';
export const CHANGE_SELECTED_TASK_ID = 'CHANGE_SELECTED_TASK_ID';
